package tn.esprit;

import com.codename1.components.ImageViewer;
import static com.codename1.ui.CN.*;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Toolbar;
import java.io.IOException;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.io.NetworkEvent;
import com.codename1.ui.Container;
import com.codename1.ui.layouts.FlowLayout;
import com.codename1.ui.util.UIBuilder;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename
 * One</a> for the purpose of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;
    private Resources theme;

    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if (err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });
    }

    public void start() {
        if (current != null) {
            current.show();
            return;
        }
        
        Form hi = new Form(new BoxLayout((BoxLayout.Y_AXIS)));
        ImageViewer head = new ImageViewer(theme.getImage("head.png"));
        hi.add(head);
        Container bodyContainer = new Container(new FlowLayout(CENTER));
        ImageViewer leftHand = new ImageViewer(theme.getImage("hand.png"));
        ImageViewer rightHand = new ImageViewer(theme.getImage("hand.png"));
        ImageViewer body = new ImageViewer(theme.getImage("body.png"));
        
        bodyContainer.addAll(leftHand, body, rightHand);
        hi.add(bodyContainer);
        
        
        Container legsContainer = new Container(new FlowLayout(CENTER));
        ImageViewer leftLeg = new ImageViewer(theme.getImage("leg.png"));
        ImageViewer rightLeg = new ImageViewer(theme.getImage("leg.png"));
        
        legsContainer.add(leftLeg);
        legsContainer.add(rightLeg);
        
        hi.add(legsContainer);
        
//        UIBuilder uib = new UIBuilder();
//        UIBuilder.registerCustomComponent("ImageViewer", ImageViewer.class);
//        Container cn = uib.createContainer(theme, "GUI 1");
//
//        hi = (Form) cn;
        

        hi.setTitle("3A42 & 3A43");
        hi.show();
    }

    public void stop() {
        current = getCurrentForm();
        if (current instanceof Dialog) {
            ((Dialog) current).dispose();
            current = getCurrentForm();
        }
    }

    public void destroy() {
    }

}
