package tn.esprit;

import com.codename1.components.OnOffSwitch;
import static com.codename1.ui.CN.*;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Button;
import com.codename1.ui.CheckBox;
import com.codename1.ui.Toolbar;
import com.codename1.ui.Container;
import com.codename1.ui.Label;
import com.codename1.ui.TextField;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.events.ActionListener;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.ui.spinner.Picker;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename
 * One</a> for the purpose of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;
    private Resources theme;

    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if (err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });
    }

    public void start() {
        if (current != null) {
            current.show();
            return;
        }
        Form hi = new Form("Inscription", BoxLayout.y());
        TextField lastNameField = new TextField("","Votre Nom");
        TextField firstNameField = new TextField("","Votre Prénom");
        TextField passwordField = new TextField("","Votre Mot de passe", 0,TextField.PASSWORD);
        Label genderLabel = new Label("Genre");
        Container genderContainer = new Container(BoxLayout.x());
        OnOffSwitch genderSwitch = new OnOffSwitch();
        genderSwitch.setOn("femme");
        genderSwitch.setOff("homme");
        
        genderContainer.addAll(genderLabel, genderSwitch);
        CheckBox foot = new CheckBox("Foot");
        CheckBox lecture = new CheckBox("Lecture");
        CheckBox tenis = new CheckBox("Tenis");
        CheckBox natation = new CheckBox("Natation");
        
        Picker datePicker = new Picker();
        Button btn = new Button("Submit");
        
        hi.addAll(lastNameField,firstNameField,passwordField,genderContainer,foot,lecture,tenis,natation,btn);
        
        btn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                
                Form f2 = new Form(new BoxLayout(BoxLayout.Y_AXIS));
                Label fnLabel = new Label("Votre nom est : " + firstNameField.getText() + " " + lastNameField.getText());
                Label passwordLabel = new Label("Votre mot de passe est : " + passwordField.getText());
                Label gender = new Label();
                if(genderSwitch.isValue() == true){
                    gender.setText("Vous êtes une femme");
                }else{
                    gender.setText("Vous êtes un homme");
                }
                String hobbies = "Vos favoris sont : ";
                if(foot.isSelected()){
                    hobbies += "foot ";
                }
                if(lecture.isSelected()){
                    hobbies += "lecture ";
                }
                if(tenis.isSelected()){
                    hobbies += "tenis ";
                }
                if(natation.isSelected()){
                    hobbies += "natation ";
                }
                Label hobbiesLabel = new Label(hobbies);
                Label naissance = new Label("Votre date de naissance est : "+datePicker.getDate());
                f2.addAll(fnLabel, passwordLabel, gender, hobbiesLabel, naissance);
                f2.show();
                
            }
        });
        
       

        hi.show();
    }

    public void stop() {
        current = getCurrentForm();
        if (current instanceof Dialog) {
            ((Dialog) current).dispose();
            current = getCurrentForm();
        }
    }

    public void destroy() {
    }

}
